# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://trumpet.db.elephantsql.com/xvjovsvi
    username: xvjovsvi
    password: pJkZ9IHgYOpMChkgq2b6PdAB5yNdgOvT
  # JPA properties
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
# Server configuration
server:
  port: 8080
# Security configuration
security:
  user:
    name: user
password: user